collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.8070176
  brandStrength: 0.5307018
  lightness: 0.8162714
  brandColors:
    - '#FFFFFF'
    - '#000700'
    - '#92917D'
    - '#595B5A'
    - '#CECE4C'
  rhythmicContrast: 0.8368748
typography_spectrum: 0.2656642
layout_spectrum: 0.8753133
name: rustysausage
